apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiaozifs-backend-api-deployment
  labels:
    apptype: jiaozifs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jiaozifs-backend-api
  template:
    metadata:
      labels:
        app: jiaozifs-backend-api
        apptype: jiaozifs-api
    spec:
      containers:
        - name: jiaozifs-backend
          image: gitdatateam/jzfs:{{ .Values.tag }}
          imagePullPolicy: Always
          args: ["--db  {{ .Values.db }} --log-level {{ .Values.log_level }} --bs_path {{ .Values.home_path }}/data --listen http://0.0.0.0:{{ .Values.port }} --config {{ .Values.home_path }}/config.yaml"]
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: jiaozifs-home
              mountPath: "/app"
      volumes:
        - name: jiaozifs-home
          persistentVolumeClaim:
            claimName: {{ .Values.claim_name }}
