apiVersion: v1
kind: Service
metadata:
  name: jiaozifs-backend-api-service
  labels:
    apptype: jiaozifs-api
spec:
  type: ClusterIP
  selector:
    app: jiaozifs-backend-api
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
