apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-jiaozifs-com-certificate
spec:
  secretName: api-jiaozifs-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.jiaozifs.com
