apiVersion: v1
kind: PersistentVolume
metadata:
  name: jiaozifs-postgres-pv-volume
  labels:
    type: local
    apptype: jiaozifs-pg-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/jiaozifs-pg-data"
