apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jiaozifs-postgres-pv-claim
  labels:
    apptype: jiaozifs-pg-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
