openapi: "3.0.0"

info:
  description: jiaozifs HTTP API
  title: jiaozifs API
  license:
    name: "Apache 2.0"
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
  - url: "/api/v1"
    description: jiaozifs server endpoint

security:
  - jwt_token: ["aaaa"]
  - basic_auth: ["aaaaa"]
components:
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
    jwt_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
    cookie_auth:
      type: apiKey
      in: cookie
      name: internal_auth_session
    oidc_auth:
      type: apiKey
      in: cookie
      name: oidc_auth_session
    saml_auth:
      type: apiKey
      in: cookie
      name: saml_auth_session
  schemas:
    VersionResult:
      type: object
      required:
        - version
        - api_version
      properties:
        version:
          type: string
          description: program version
        api_version:
          type: string
          description: runtime version
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: short message explaining the error
          type: string
paths:
  /version:
    get:
      tags:
        - common
      operationId: getVersion
      summary: return program and runtime version
      security:
        - jwt_token: []
      responses:
        200:
          description: program version
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VersionResult"

