openapi: "3.0.0"

info:
  description: lakeFS HTTP API
  title: lakeFS API
  license:
    name: "Apache 2.0"
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
  - url: "/api/v1"
    description: lakeFS server endpoint
security:
  - jwt_token: []
components:
  securitySchemes:
    jwt_token:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    PaginationPrefix:
      in: query
      name: prefix
      description: return items prefixed with this value
      schema:
        type: string

  responses:
    NotFoundOrNoACL:
      description: Group not found, or group found but has no ACL
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Pagination"

  schemas:
    Pagination:
      type: object
      required:
        - has_more
        - max_per_page
        - results
        - next_offset
      properties:
        has_more:
          type: boolean
          description: Next page is available
        next_offset:
          type: string
          description: Token used to retrieve the next page
        results:
          type: integer
          minimum: 0
          description: Number of values found in the results
        max_per_page:
          type: integer
          minimum: 0
          description: Maximal number of entries per page
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: short message explaining the error
          type: string
paths:
  /setup_comm_prefs:
    post:
      tags:
        - internal
      operationId: setupCommPrefs
      summary: setup communications preferences
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Error"
      responses:
        200:
          description: communication preferences saved successfully
        409:
          description: setup was already completed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        412:
          description: wrong setup state for this operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        420:
          description: too many requests
        default:
          $ref: "#/components/schemas/Error"