openapi: "3.0.0"

info:
  description: lakeFS HTTP API
  title: lakeFS API
  license:
    name: "Apache 2.0"
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
  - url: "/api/v1"
    description: lakeFS server endpoint
components:
  schemas:
    VersionResult:
      type: object
      required:
        - version
        - api_version
      properties:
        version:
          type: string
          description: program version
        api_version:
          type: string
          description: runtime version
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: short message explaining the error
          type: string
paths:
  /version:
    get:
      tags:
        - common
      operationId: getVersion
      summary: return program and runtime version
      responses:
        200:
          description: program version
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VersionResult"

