name: basic-check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.9'
          cache: true

      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get -o Acquire::Retries=3 install make gcc git curl wget -y

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        run: |
          make build

      - name: end-of-file-check
        uses: njgibbon/fend@main

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -d -b $(go env GOPATH)/bin v1.55.1
          golangci-lint run --timeout 10m

      - name: Detect changes
        run: |
          git status --porcelain
          test -z "$(git status --porcelain)"
