name: test

on:
  push:
    branches:
      - master
      - 'deployment/**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.9'
          cache: true

      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get -o Acquire::Retries=3 install make gcc git curl wget -y

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org,direct"
          GO111MODULE: "on"
        run: |
          make build

      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 12
      - run: |
          docker version

      - name: Test
        run: |
          go test -coverpkg=./... -coverprofile=coverage.out -covermode=atomic -timeout=30m -parallel=4  -v ./...

      - name: Upload
        uses: codecov/codecov-action@v3
        with:
          token:
          files: ./coverage.out
          name: jzfs
          fail_ci_if_error: true
          verbose: true
  deployment:
    if: ${{ startsWith(github.ref, 'deployment/') || github.ref == 'master' }}
    runs-on: [self-hosted]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        run: |
          echo ${{ secrets.DOCKERHUB_USERNAME }}
          echo ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jiaozifs/jiaozifs:{{}}